spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: adminroot
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
